apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "connect-live-info-ncaaf.fullname" . }}
spec:
  schedule: {{ .Values.cronJob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: {{ .Values.global.repository }}/{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
            {{- range .Values.cronJob.command }}
            - {{ . | quote }}
            {{- end }}
            env:
            {{- range $key, $value := .Values.image.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
            - name: CONNECT_EP
              value: "{{ .Release.Name }}-connect.default.svc.cluster.local:8083"
            resources:
              limits:  
                cpu: {{ .Values.deployment.resources.maxCpu }}
                memory: {{ .Values.deployment.resources.maxMem }}
              requests:
                cpu: {{ .Values.deployment.resources.minCpu }}
                memory: {{ .Values.deployment.resources.minMem }}
          terminationGracePeriodSeconds: 10
          restartPolicy: {{ .Values.cronJob.restartPolicy }}
